server:
  port: 80
spring:
  application:
    name: bobi
  #数据库连接信息
  datasource:
    name: ds1
    url: jdbc:mysql://sh-cynosdbmysql-grp-m1sf60z6.sql.tencentcdb.com:25942/pet?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT&allowPublicKeyRetrieval=true
    username: root
    password: Ldw@123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  http:
    multipart:
      maxFileSize: 50Mb
      maxRequestSize: 50Mb
